# Generated by Django 2.0.4 on 2018-04-21 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_food', models.DecimalField(decimal_places=2, max_digits=4)),
                ('newborn_screening', models.DecimalField(decimal_places=2, max_digits=4)),
                ('infants_received_vitamin_A', models.DecimalField(decimal_places=2, max_digits=4)),
                ('infants_received_iron', models.DecimalField(decimal_places=2, max_digits=4)),
                ('infants_received_MNP', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sick_children', models.DecimalField(decimal_places=2, max_digits=4)),
                ('given_deworming', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anemic_children', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anemic_with_iron', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diarrhea_cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diarrhea_with_ors', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pneumonia_cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pneumonia_with_tx', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FHSIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datacollection.Barangay')),
            ],
            options={
                'verbose_name_plural': 'FHSIS',
            },
        ),
        migrations.CreateModel(
            name='Flariasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('clinical_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mfd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('given_mda', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareWasteManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('with_syringe', models.DecimalField(decimal_places=2, max_digits=4)),
                ('with_safe_water', models.DecimalField(decimal_places=2, max_digits=4)),
                ('with_sanitary_toilet', models.DecimalField(decimal_places=2, max_digits=4)),
                ('with_waste_disposal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('with_basic_sanitation', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunization_given', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fully_immunized_child', models.DecimalField(decimal_places=2, max_digits=4)),
                ('child_protected', models.DecimalField(decimal_places=2, max_digits=4)),
                ('infant_breastfed_until_6th_month', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='InformalSettlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('families', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Leprosy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cases_cured', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='Malaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_at_risk', models.DecimalField(decimal_places=2, max_digits=4)),
                ('confirmed_malaria_cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('malarial_deaths', models.DecimalField(decimal_places=2, max_digits=4)),
                ('llin_given', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='Maternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_with_4_or_more_prenatal_visits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_given_2_tt_doses', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_given_tt2plus', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_given_iron_with_supplementation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_with_atleast_2_postpartum_visits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_with_vitamin_A', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_breastfed_1_hour_after_delivery', models.DecimalField(decimal_places=2, max_digits=4)),
                ('women_given_iron', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deliveries', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'nutritional statuses',
            },
        ),
        migrations.CreateModel(
            name='OperationTimbang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datacollection.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='OPTValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=0, max_digits=7)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datacollection.AgeGroup')),
                ('nutritional_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datacollection.NutritionalStatus')),
                ('opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.OperationTimbang')),
            ],
            options={
                'verbose_name_plural': 'OPT Values',
            },
        ),
        migrations.CreateModel(
            name='Schistosomiasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_treated', models.DecimalField(decimal_places=2, max_digits=4)),
                ('positive_cases', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='STISurveillance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant_women_seen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pregnant_women_syphilis_positive', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pregnant_women_given_penicillin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underwent_DDSM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('smear_discovered', models.DecimalField(decimal_places=2, max_digits=4)),
                ('smear_cured', models.DecimalField(decimal_places=2, max_digits=4)),
                ('case_detection_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('all_forms_identified', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.AgeGroup')),
                ('fhsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS')),
            ],
        ),
        migrations.CreateModel(
            name='UnemploymentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='childcare',
            name='fhsis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollection.FHSIS'),
        ),
    ]
