# Generated by Django 2.0.4 on 2018-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternal',
            name='women_with_4_or_more_prenatal_visits',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Woman with 4 or more Prenatal Visits'),
        ),
    ]
