# Generated by Django 2.0.4 on 2018-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_auto_20180421_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunization',
            old_name='fully_immunized_child',
            new_name='fully_immunized_children',
        ),
        migrations.AlterField(
            model_name='childcare',
            name='given_food',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Given complimentary food'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='infants_received_MNP',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Infants who received MNP'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='infants_received_iron',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Infants who received Iron'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='infants_received_vitamin_A',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Infants who received Vitamin A'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='newborn_screening',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Infant for newborn screening'),
        ),
        migrations.AlterField(
            model_name='flariasis',
            name='given_mda',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Number of people given MDA'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='child_protected',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Child protected at birth'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='infant_breastfed_until_6th_month',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Infant exclusively breastfed until 6th month'),
        ),
        migrations.AlterField(
            model_name='informalsettlers',
            name='families',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Number of families'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='deliveries',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Deliveries'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_breastfed_1_hour_after_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Postpartum women initiated breastfeeding within 1 hour after delivery'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_given_2_tt_doses',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pregnant women given 2 doses of Tetanus Toxoid'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_given_iron',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Women 10-49 years old given iron supplementation'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_given_iron_with_supplementation',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pregnant women given complete iron with folic acid supplementation'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_given_tt2plus',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pregnant women given TT2 plus'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_with_4_or_more_prenatal_visits',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pregnant women with 4 or more Prenatal Visits'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_with_atleast_2_postpartum_visits',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Postpartum women with at least 2 postpartum visits'),
        ),
        migrations.AlterField(
            model_name='maternal',
            name='women_with_vitamin_A',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Postpartum women given Vitamin A supplementation'),
        ),
    ]
