# Generated by Django 2.0.4 on 2018-04-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20180425_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='child_protected',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Child protected at birth'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='fully_immunized_children',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='immunization_given',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='infant_breastfed_until_6th_month',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Infant exclusively breastfed until 6th month'),
        ),
        migrations.AlterField(
            model_name='leprosy',
            name='cases',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='leprosy',
            name='cases_cured',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='confirmed_malaria_cases',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='llin_given',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='malarial_deaths',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='population_at_risk',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='schistosomiasis',
            name='cases_treated',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='schistosomiasis',
            name='positive_cases',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='all_forms_identified',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='case_detection_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='smear_cured',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='smear_discovered',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='underwent_DDSM',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
